export const INDIAN_STATES_CITIES = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Tirupati", "Rajahmundry"],
  "Arunachal Pradesh": ["Itanagar"],
  "Assam": ["Guwahati", "Dibrugarh", "Silchar", "Jorhat"],
  "Bihar": ["Patna", "Gaya", "Darbhanga"],
  "Chandigarh": ["Chandigarh"],
  "Chhattisgarh": ["Raipur", "Bilaspur"],
  "Delhi": ["New Delhi"],
  "Goa": ["Panaji", "Vasco da Gama", "Dabolim", "Margao"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar"],
  "Haryana": ["Gurgaon", "Faridabad", "Ambala"],
  "Himachal Pradesh": ["Shimla", "Kullu", "Dharamshala"],
  "Jammu & Kashmir": ["Srinagar", "Jammu"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad"],
  "Karnataka": ["Bangalore", "Mangalore", "Mysore", "Hubli", "Belgaum"],
  "Kerala": ["Kochi", "Trivandrum", "Kozhikode", "Kannur"],
  "Madhya Pradesh": ["Indore", "Bhopal", "Gwalior", "Jabalpur"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Aurangabad", "Nashik", "Shirdi"],
  "Manipur": ["Imphal"],
  "Meghalaya": ["Shillong"],
  "Mizoram": ["Aizawl"],
  "Nagaland": ["Dimapur", "Kohima"],
  "Odisha": ["Bhubaneswar", "Jharsuguda"],
  "Punjab": ["Amritsar", "Ludhiana", "Jalandhar", "Pathankot"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Bikaner", "Ajmer", "Kota"],
  "Sikkim": ["Gangtok"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Trichy", "Salem", "Tuticorin"],
  "Telangana": ["Hyderabad", "Warangal"],
  "Tripura": ["Agartala"],
  "Uttar Pradesh": ["Lucknow", "Varanasi", "Agra", "Kanpur", "Prayagraj", "Gorakhpur", "Bareilly"],
  "Uttarakhand": ["Dehradun", "Pantnagar"],
  "West Bengal": ["Kolkate", "Siliguri", "Durgapur", "Bagdogra"]
};
